model:
  # Model specific settings, do not change!
  model: "SwinUnet"  # Should be the same name as parent config folder
  run_name: "SwinUnet2025May23HLR"  # Such that the run can be recognized, i.e., start date
  input_shape: [256, 256, 4]
  output_shape: [256, 256, 1]

sys_config:
  n_cpu_cores: 14 # Number of CPU cores to use in parallel processing

data:
  # Data specific settings, change to needs.
  test_dataset_path: "/mnt/g/data/PhD Projects/SR/cosmos/cosmos_spitzer_spire/Test"
  test_batch_size: 36 # Batch size for test data, can be larger than train batch size
  input: ["24", "250", "350", "500"]  # class names
  target: ["500SR"]  # class names
